#!/bin/bash
# ════════════════════════════════════════════════════════════════════
#  FEROKE VANGUARD — JETSON ONE-TIME INSTALLER
#  Run ONCE after first copying the project to the Jetson:
#    chmod +x install_jetson.sh
#    ./install_jetson.sh
#
#  This script:
#    1. Installs all system & Python dependencies
#    2. Compiles the TensorRT engine for maximum GPU performance
#    3. Registers Feroke as an autostart desktop application
# ════════════════════════════════════════════════════════════════════

set -e   # Exit immediately on any error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LITE_DIR="$SCRIPT_DIR/Feroke-Traffic-Lite"
JETSON_DIR="$SCRIPT_DIR/Feroke-Traffic-Jetson"
MODEL_PT="$LITE_DIR/models/nano_edge.pt"
MODEL_ENGINE="$LITE_DIR/models/nano_edge.engine"

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  FEROKE VANGUARD — JETSON INSTALL SYSTEM"
echo "════════════════════════════════════════════════════════════"
echo ""

# ── Step 1: System packages ─────────────────────────────────────
echo "▶ [1/4] Installing system dependencies..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    python3-pip python3-setuptools python3-venv \
    libxcb-cursor0 libxcb-icccm4 libxcb-image0 \
    libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 \
    libxcb-xkb1 libxkbcommon-x11-0 \
    libglib2.0-0 libsm6 libxext6 libxrender-dev \
    libgl1-mesa-glx \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools libgstreamer1.0-dev
echo "✅ System packages installed."

# ── Step 2: Python packages ──────────────────────────────────────
echo ""
echo "▶ [2/4] Installing Python packages..."
python3 -m pip install --upgrade pip --quiet
python3 -m pip install -r "$JETSON_DIR/requirements.txt" --quiet
echo "✅ Python packages installed."

# ── Step 3: TensorRT Engine Compilation ─────────────────────────
echo ""
echo "▶ [3/4] Checking TensorRT engine..."
mkdir -p "$LITE_DIR/models"

if [ ! -f "$MODEL_ENGINE" ]; then
    if [ -f "$MODEL_PT" ]; then
        echo "   🔄 Compiling nano_edge.pt → nano_edge.engine"
        echo "   ⏳ This takes ~5-10 minutes on Jetson Nano. PLEASE WAIT..."
        echo "   ⚡ Maximizing clocks for compilation..."
        sudo jetson_clocks 2>/dev/null || echo "   (jetson_clocks not found, skipping)"

        cd "$LITE_DIR"
        python3 -c "
from ultralytics import YOLO
model = YOLO('models/nano_edge.pt')
model.export(format='engine', device=0, half=True, imgsz=416)
print('✅ TensorRT engine compiled successfully!')
"
        cd "$SCRIPT_DIR"
    else
        echo "   ⚠️  Model file not found at $MODEL_PT — skipping compilation."
        echo "      Place your nano_edge.pt in Feroke-Traffic-Lite/models/ and re-run."
    fi
else
    echo "   ⚡ TensorRT engine already exists — skipping compilation."
fi

# ── Step 4: Autostart Registration ──────────────────────────────
echo ""
echo "▶ [4/4] Registering Feroke as autostart application..."

# Create the launcher script
LAUNCHER="$SCRIPT_DIR/feroke_launch.sh"
cat > "$LAUNCHER" << LAUNCH_EOF
#!/bin/bash
# Auto-generated by install_jetson.sh
export DISPLAY=:0
export XDG_RUNTIME_DIR=/run/user/\$(id -u)

# Maximize GPU & CPU clocks for performance
sudo jetson_clocks 2>/dev/null || true

# Wait for X display to be ready
for i in {1..15}; do
    xdpyinfo -display :0 >/dev/null 2>&1 && break
    echo "Waiting for display... (\$i/15)"
    sleep 2
done

cd "$LITE_DIR"
python3 feroke_desktop.py

# If desktop GUI fails, fall back to web server
if [ \$? -ne 0 ]; then
    echo "GUI failed — starting web server fallback on port 8000..."
    python3 feroke_inference.py
fi
LAUNCH_EOF
chmod +x "$LAUNCHER"

# Create .desktop autostart entry
AUTOSTART_DIR="$HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"
cat > "$AUTOSTART_DIR/feroke-vanguard.desktop" << DESKTOP_EOF
[Desktop Entry]
Type=Application
Name=Feroke Vanguard
Comment=AI Traffic Analysis System
Exec=bash $LAUNCHER
Icon=utilities-terminal
Terminal=false
X-GNOME-Autostart-enabled=true
DESKTOP_EOF

echo "✅ Autostart registered at: $AUTOSTART_DIR/feroke-vanguard.desktop"

# Also create a convenient desktop shortcut
DESKTOP_FILE="$HOME/Desktop/Feroke-Vanguard.desktop"
if [ -d "$HOME/Desktop" ]; then
    cp "$AUTOSTART_DIR/feroke-vanguard.desktop" "$DESKTOP_FILE"
    chmod +x "$DESKTOP_FILE"
    echo "✅ Desktop shortcut created."
fi

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  ✅ INSTALLATION COMPLETE!"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  WHAT WAS SET UP:"
echo "   • All Python & system dependencies installed"
echo "   • TensorRT engine compiled (if model was present)"
echo "   • Feroke will AUTO-START on every boot"
echo "   • Desktop shortcut created (if Desktop folder exists)"
echo ""
echo "  TO START NOW (without rebooting):"
echo "   bash $LAUNCHER"
echo ""
echo "  TO DISABLE AUTOSTART:"
echo "   rm $AUTOSTART_DIR/feroke-vanguard.desktop"
echo ""
echo "  EDIT CAMERAS: Edit $LITE_DIR/config.py"
echo "════════════════════════════════════════════════════════════"
echo ""
